const path=require('path');const http=require('http');const express=require('express');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const {Pool}=require('pg');const {WebSocketServer}=require('ws');
const PORT=Number(process.env.PORT||10000), JWT_SECRET=process.env.JWT_SECRET||'dev-secret-change-me';
const app=express(),server=http.createServer(app);app.use(express.json({limit:'3mb'}));app.use(express.static(path.join(__dirname,'public')));
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false}):null;
const demoUsers=new Map();const demoGames=new Map();let demoId=1;
async function query(sql,args=[]){if(!pool) throw new Error('DATABASE_URL is not configured. Set it in .env for persistent mode.');return pool.query(sql,args)}
async function init(){if(!pool)return;await query(`CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,username VARCHAR(24) UNIQUE NOT NULL,password_hash TEXT NOT NULL,display_name VARCHAR(32) NOT NULL,avatar JSONB NOT NULL DEFAULT '{}'::jsonb,inventory JSONB NOT NULL DEFAULT '[]'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS games(id BIGSERIAL PRIMARY KEY,owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name VARCHAR(80) NOT NULL,description TEXT NOT NULL DEFAULT '',thumbnail TEXT NOT NULL DEFAULT '',data JSONB NOT NULL DEFAULT '{}'::jsonb,is_public BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE INDEX IF NOT EXISTS games_public_idx ON games(is_public);`)}
function token(u){return jwt.sign({id:u.id,username:u.username},JWT_SECRET,{expiresIn:'7d'})}function auth(req,res,next){const h=req.headers.authorization||'';try{if(!h.startsWith('Bearer '))throw 0;req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch{res.status(401).json({error:'Inicia sesión para continuar.'})}}
app.get('/api/health',async(req,res)=>{let database='demo';if(pool){try{await query('SELECT 1');database='postgresql'}catch{database='error'}}res.json({ok:true,service:'Kavora',database})});
app.post('/api/auth/register',async(req,res)=>{try{const {username,password,displayName}=req.body;if(!/^[A-Za-z0-9_]{3,24}$/.test(username||''))return res.status(400).json({error:'El usuario debe tener 3-24 caracteres.'});if((password||'').length<8)return res.status(400).json({error:'La contraseña debe tener al menos 8 caracteres.'});if(pool){const hash=await bcrypt.hash(password,12);const r=await query('INSERT INTO users(username,password_hash,display_name) VALUES($1,$2,$3) RETURNING id,username,display_name,avatar,inventory',[username,hash,displayName||username]);return res.json({token:token(r.rows[0]),user:r.rows[0]})}if(demoUsers.has(username))return res.status(409).json({error:'Ese usuario ya existe.'});const u={id:demoId++,username,passwordHash:await bcrypt.hash(password,10),display_name:displayName||username,avatar:{face:'default',color:'#2b8cff'},inventory:[]};demoUsers.set(username,u);res.json({token:token(u),user:u})}catch(e){if(e.code==='23505')return res.status(409).json({error:'Ese usuario ya existe.'});console.error(e);res.status(500).json({error:'No se pudo crear la cuenta.'})}});
app.post('/api/auth/login',async(req,res)=>{try{const {username,password}=req.body;let u;if(pool){const r=await query('SELECT * FROM users WHERE username=$1',[username]);u=r.rows[0]}else u=demoUsers.get(username);if(!u||!(await bcrypt.compare(password||'',u.password_hash||u.passwordHash)))return res.status(401).json({error:'Usuario o contraseña incorrectos.'});res.json({token:token(u),user:{id:u.id,username:u.username,display_name:u.display_name,avatar:u.avatar||{},inventory:u.inventory||[]}})}catch(e){res.status(500).json({error:'No se pudo iniciar sesión.'})}});
app.get('/api/me',auth,async(req,res)=>{try{if(pool){const r=await query('SELECT id,username,display_name,avatar,inventory,created_at FROM users WHERE id=$1',[req.user.id]);if(!r.rows[0])return res.status(404).json({error:'Cuenta no encontrada.'});return res.json({user:r.rows[0]})}const u=[...demoUsers.values()].find(x=>x.id===req.user.id);if(!u)return res.status(404).json({error:'Cuenta no encontrada.'});res.json({user:u})}catch(e){res.status(500).json({error:'No se pudo cargar el perfil.'})}});
app.put('/api/me/avatar',auth,async(req,res)=>{try{const avatar=req.body.avatar||{};if(pool){const r=await query('UPDATE users SET avatar=$1 WHERE id=$2 RETURNING avatar',[JSON.stringify(avatar),req.user.id]);return res.json({avatar:r.rows[0].avatar})}const u=[...demoUsers.values()].find(x=>x.id===req.user.id);u.avatar=avatar;res.json({avatar})}catch(e){res.status(500).json({error:'No se pudo guardar el avatar.'})}});
app.get('/api/games',async(req,res)=>{try{if(pool){const r=await query('SELECT g.id,g.name,g.description,g.thumbnail,g.owner_id,u.username AS owner,g.data FROM games g JOIN users u ON u.id=g.owner_id WHERE g.is_public=true ORDER BY g.updated_at DESC LIMIT 50');return res.json({games:r.rows})}res.json({games:[...demoGames.values()].filter(g=>g.is_public).sort((a,b)=>b.id-a.id)})}catch(e){res.status(500).json({error:'No se pudieron cargar los juegos.'})}});
app.get('/api/my-games',auth,async(req,res)=>{try{if(pool){const r=await query('SELECT * FROM games WHERE owner_id=$1 ORDER BY updated_at DESC',[req.user.id]);return res.json({games:r.rows})}res.json({games:[...demoGames.values()].filter(g=>g.owner_id===req.user.id)})}catch(e){res.status(500).json({error:'No se pudieron cargar tus juegos.'})}});
app.post('/api/games',auth,async(req,res)=>{try{const {name,description,thumbnail,data,isPublic}=req.body;if(!name||name.length>80)return res.status(400).json({error:'Nombre de juego inválido.'});if(pool){const r=await query('INSERT INTO games(owner_id,name,description,thumbnail,data,is_public) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[req.user.id,name,description||'',thumbnail||'',JSON.stringify(data||{}),!!isPublic]);return res.json({game:r.rows[0]})}const g={id:demoId++,owner_id:req.user.id,owner:req.user.username,name,description:description||'',thumbnail:thumbnail||'',data:data||{},is_public:!!isPublic};demoGames.set(g.id,g);res.json({game:g})}catch(e){console.error(e);res.status(500).json({error:'No se pudo publicar el juego.'})}});
const wss=new WebSocketServer({server,path:'/ws'}),rooms=new Map();function broadcast(room,msg){const s=JSON.stringify(msg);for(const p of room.values())if(p.ws.readyState===1)p.ws.send(s)}
wss.on('connection',(ws,req)=>{const u=new URL(req.url,'http://localhost');const game=u.searchParams.get('game')||'demo';if(!rooms.has(game))rooms.set(game,new Map());const room=rooms.get(game),id=Math.random().toString(36).slice(2,9),player={id,x:80+Math.random()*300,y:80+Math.random()*300,name:'Player'};room.set(id,{ws,player});ws.send(JSON.stringify({type:'welcome',playerId:id,players:[...room.values()].map(x=>x.player)}));broadcast(room,{type:'join',player});ws.on('message',raw=>{try{const m=JSON.parse(raw);if(m.type==='move'){player.x=Math.max(0,Math.min(1000,Number(m.x)||0));player.y=Math.max(0,Math.min(560,Number(m.y)||0));broadcast(room,{type:'move',player})}}catch{}});ws.on('close',()=>{room.delete(id);broadcast(room,{type:'leave',playerId:id});if(!room.size)rooms.delete(game)})});
app.get('*',(req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).json({error:'Not found'});res.sendFile(path.join(__dirname,'public','index.html'))});
init().then(()=>server.listen(PORT,'0.0.0.0',()=>console.log('Kavora V2 on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
